<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
      <UserSecretsId>738cba68-087c-4418-9cbf-c886fc86e643</UserSecretsId>
  </PropertyGroup>
    

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.19" />
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.19" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.19">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Scalar.AspNetCore" Version="2.17.1" />
    </ItemGroup>
    

    <ItemGroup>
      <ProjectReference Include="..\GameStore.Application\GameStore.Application.csproj" />
      <ProjectReference Include="..\GameStore.Infrastructure\GameStore.Infrastructure.csproj" />
    </ItemGroup>

</Project>
